# Generated by Django 5.0.6 on 2024-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='number',
            field=models.IntegerField(),
        ),
    ]
