# Generated by Django 5.0.6 on 2024-06-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_alter_portfolio_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioprojects',
            old_name='titel',
            new_name='title',
        ),
    ]
