# Generated by Django 5.0.6 on 2024-06-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0004_alter_portfolio_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprojects',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioProjects',
        ),
    ]
