# Generated by Django 5.0.6 on 2024-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('media', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
