# Generated by Django 5.0.6 on 2024-06-21 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announsements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announsement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='announsements.announsement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_Announsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announsement', 'user')},
            },
        ),
    ]
