# Generated by Django 5.0.6 on 2024-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announsements', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announsement',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
