# Generated by Django 5.0.6 on 2024-06-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announsements', '0003_alter_announsement_media'),
        ('portfolio', '0001_initial'),
        ('pro_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='announcements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announsements.announsement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioprojects'),
        ),
    ]
