# Generated by Django 5.0.6 on 2024-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_file', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile_picture.jpg', null=True, upload_to='images/profile_photo'),
        ),
    ]
